import type { EchoNodeDef } from '../types/roguelike.js'

/**
 * Echo Tree — permanent upgrades purchased with Commit Echoes.
 *
 * Three branches:
 *   - foundations: scaling stat boosts (many ranks)
 *   - unlocks:     one-shot content unlocks (relics, modifiers, Kin, layer bonuses)
 *   - mutations:   rule-changing upgrades (expensive, one-shot)
 *
 * Scales to ~30 prestiges before the tree is saturated.
 */
export const ECHO_NODE_DEFS: readonly EchoNodeDef[] = [
  // ── FOUNDATIONS (20 nodes) ─────────────────────────────────
  {
    id: 'foundations_mote_value',
    category: 'foundations',
    name: 'Denser Motes',
    description: '+5% Token value per rank.',
    baseCost: 1,
    maxRank: 10,
    grant: { kind: 'stat_mote_value', value: 0.05 },
  },
  {
    id: 'foundations_starting_tokens',
    category: 'foundations',
    name: 'Primed Reserves',
    description: '+10 starting Tokens per rank.',
    baseCost: 2,
    maxRank: 10,
    grant: { kind: 'stat_starting_tokens', value: 10 },
  },
  {
    id: 'foundations_expedition_speed',
    category: 'foundations',
    name: 'Path Memory',
    description: '-5% expedition duration per rank.',
    baseCost: 2,
    maxRank: 8,
    grant: { kind: 'stat_expedition_speed', value: 0.05 },
  },
  {
    id: 'foundations_kin_cap',
    category: 'foundations',
    name: 'Open Gates',
    description: '+1 starting Kin per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_kin_cap', value: 1 },
  },
  {
    id: 'foundations_warden_dmg',
    category: 'foundations',
    name: 'Sharp Edge',
    description: '+5% Warden damage per rank.',
    baseCost: 2,
    maxRank: 8,
    grant: { kind: 'stat_warden_dmg', value: 0.05 },
  },
  {
    id: 'foundations_shard_gain',
    category: 'foundations',
    name: 'Deeper Veins',
    description: '+5% shards from glitches per rank.',
    baseCost: 2,
    maxRank: 10,
    grant: { kind: 'stat_shard_gain', value: 0.05 },
  },
  {
    id: 'foundations_focus_gain',
    category: 'foundations',
    name: 'Sharper Focus',
    description: '+5% Focus from fixes per rank.',
    baseCost: 2,
    maxRank: 8,
    grant: { kind: 'stat_focus_gain', value: 0.05 },
  },
  {
    id: 'foundations_passive_trickle',
    category: 'foundations',
    name: 'Steady Pulse',
    description: '+10% passive mote rain per rank.',
    baseCost: 2,
    maxRank: 6,
    grant: { kind: 'stat_passive_trickle', value: 0.1 },
  },
  {
    id: 'foundations_echoes_gain',
    category: 'foundations',
    name: 'Ringing Memory',
    description: '+5% Echoes earned on prestige per rank.',
    baseCost: 4,
    maxRank: 8,
    grant: { kind: 'stat_echoes_gain', value: 0.05 },
  },
  {
    id: 'foundations_expedition_fail',
    category: 'foundations',
    name: 'Surefoot',
    description: '-1% expedition fail rate per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_expedition_fail', value: 0.01 },
  },
  {
    id: 'foundations_commit_shards',
    category: 'foundations',
    name: 'Ritual Commits',
    description: '+1 shard per commit, per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_commit_shards', value: 1 },
  },
  {
    id: 'foundations_layer_stability',
    category: 'foundations',
    name: 'Reinforced Floors',
    description: '+10 max layer stability per rank.',
    baseCost: 2,
    maxRank: 5,
    grant: { kind: 'stat_layer_stability', value: 10 },
  },
  {
    id: 'foundations_boss_dmg',
    category: 'foundations',
    name: "Watcher's Bane",
    description: '+5% damage to bosses per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_boss_dmg', value: 0.05 },
  },
  {
    id: 'foundations_kin_hp',
    category: 'foundations',
    name: 'Hardened Kin',
    description: '+10% Kin HP per rank.',
    baseCost: 2,
    maxRank: 8,
    grant: { kind: 'stat_kin_hp', value: 0.1 },
  },
  {
    id: 'foundations_glitch_hp',
    category: 'foundations',
    name: 'Weakening Field',
    description: '-5% glitch HP per rank.',
    baseCost: 3,
    maxRank: 6,
    grant: { kind: 'stat_glitch_hp', value: 0.05 },
  },
  {
    id: 'foundations_focus_regen',
    category: 'foundations',
    name: 'Resting Core',
    description: '+1 passive Focus/min per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_focus_regen', value: 1 },
  },
  {
    id: 'foundations_dusk_multiplier',
    category: 'foundations',
    name: 'Long Twilight',
    description: '+10% dusk duration per rank.',
    baseCost: 3,
    maxRank: 5,
    grant: { kind: 'stat_dusk_duration', value: 0.1 },
  },
  {
    id: 'foundations_wave_delay',
    category: 'foundations',
    name: 'Breathing Room',
    description: '+5% wave interval per rank.',
    baseCost: 2,
    maxRank: 5,
    grant: { kind: 'stat_wave_delay', value: 0.05 },
  },
  {
    id: 'foundations_starting_shards',
    category: 'foundations',
    name: 'Seed Shards',
    description: '+2 starting shards per rank.',
    baseCost: 2,
    maxRank: 5,
    grant: { kind: 'stat_starting_shards', value: 2 },
  },
  {
    id: 'foundations_relic_power',
    category: 'foundations',
    name: 'Resonance',
    description: '+10% relic effect per rank.',
    baseCost: 5,
    maxRank: 3,
    grant: { kind: 'stat_relic_power', value: 0.1 },
  },

  // ── UNLOCKS (20 nodes) ─────────────────────────────────────
  {
    id: 'unlock_relic_commit_mirror',
    category: 'unlocks',
    name: 'Relic: Commit Mirror',
    description: 'Adds Commit Mirror to the drop pool.',
    baseCost: 5,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'commit_mirror' },
  },
  {
    id: 'unlock_relic_warden_promise',
    category: 'unlocks',
    name: "Relic: Warden's Promise",
    description: 'Adds Warden\'s Promise to the drop pool.',
    baseCost: 5,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'warden_promise' },
  },
  {
    id: 'unlock_relic_focus_prism',
    category: 'unlocks',
    name: 'Relic: Focus Prism',
    description: 'Adds Focus Prism to the drop pool.',
    baseCost: 6,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'focus_prism' },
  },
  {
    id: 'unlock_relic_aria_whisper',
    category: 'unlocks',
    name: "Relic: ARIA's Whisper",
    description: 'Adds the legendary ARIA relic to the pool.',
    baseCost: 15,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'aria_whisper' },
  },
  {
    id: 'unlock_relic_drama_mask',
    category: 'unlocks',
    name: 'Relic: Drama Mask',
    description: 'Adds Drama Mask (legendary).',
    baseCost: 15,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'drama_mask' },
  },
  {
    id: 'unlock_relic_echo_lantern',
    category: 'unlocks',
    name: 'Relic: Echo Lantern',
    description: 'Adds Echo Lantern (legendary).',
    baseCost: 20,
    maxRank: 1,
    grant: { kind: 'unlock_relic', target: 'echo_lantern' },
  },
  {
    id: 'unlock_modifier_glass_core',
    category: 'unlocks',
    name: 'Modifier: Glass Core',
    description: 'Unlocks the high-risk Glass Core run modifier.',
    baseCost: 8,
    maxRank: 1,
    grant: { kind: 'unlock_modifier', target: 'glass_core' },
  },
  {
    id: 'unlock_modifier_blind_descent',
    category: 'unlocks',
    name: 'Modifier: Blind Descent',
    description: 'Unlocks Blind Descent.',
    baseCost: 12,
    maxRank: 1,
    grant: { kind: 'unlock_modifier', target: 'blind_descent' },
  },
  {
    id: 'unlock_modifier_perma_night',
    category: 'unlocks',
    name: 'Modifier: Perma-Night',
    description: 'Unlocks Perma-Night.',
    baseCost: 12,
    maxRank: 1,
    grant: { kind: 'unlock_modifier', target: 'perma_night' },
  },
  {
    id: 'unlock_modifier_dual_expeditions',
    category: 'unlocks',
    name: 'Modifier: Dual Expeditions',
    description: 'Unlocks Dual Expeditions.',
    baseCost: 10,
    maxRank: 1,
    grant: { kind: 'unlock_modifier', target: 'dual_expeditions' },
  },
  {
    id: 'unlock_relic_slot',
    category: 'unlocks',
    name: 'Extra Relic Slot',
    description: '+1 equipped Relic slot (max 5).',
    baseCost: 10,
    maxRank: 2,
    grant: { kind: 'unlock_relic_slot', value: 1 },
  },
  {
    id: 'unlock_kin_archivist',
    category: 'unlocks',
    name: 'Kin: Archivist',
    description: 'The Archivist collects idle loot and recites old commits.',
    baseCost: 12,
    maxRank: 1,
    grant: { kind: 'unlock_kin', target: 'archivist' },
  },
  {
    id: 'unlock_layer_bonus_void',
    category: 'unlocks',
    name: 'Bonus Layer: Recursion Void',
    description: 'A hidden layer between Deep and Abyss.',
    baseCost: 20,
    maxRank: 1,
    grant: { kind: 'unlock_layer_bonus', target: 'recursion_void' },
  },
  {
    id: 'unlock_focus_ability_echo_strike',
    category: 'unlocks',
    name: 'Focus: Echo Strike',
    description: 'New Focus ability that chains lances.',
    baseCost: 8,
    maxRank: 1,
    grant: { kind: 'unlock_focus_ability', target: 'echo_strike' },
  },
  {
    id: 'unlock_focus_ability_timestop',
    category: 'unlocks',
    name: 'Focus: Timestop',
    description: 'Freezes glitches for 3 seconds.',
    baseCost: 14,
    maxRank: 1,
    grant: { kind: 'unlock_focus_ability', target: 'timestop' },
  },
  {
    id: 'unlock_expedition_event_rare_ruin',
    category: 'unlocks',
    name: 'Expedition: Ruined Codex',
    description: 'Adds a rare expedition event that drops a legendary relic.',
    baseCost: 15,
    maxRank: 1,
    grant: { kind: 'unlock_expedition_event', target: 'ruined_codex' },
  },
  {
    id: 'unlock_boss_variant_merge',
    category: 'unlocks',
    name: 'Boss Variant: Merge Fury',
    description: 'Adds a second moveset for the main boss.',
    baseCost: 18,
    maxRank: 1,
    grant: { kind: 'unlock_boss_variant', target: 'merge_fury' },
  },
  {
    id: 'unlock_auto_relic_pickup',
    category: 'unlocks',
    name: 'Auto-Relic',
    description: 'Expedition relics auto-equip if a slot is free.',
    baseCost: 8,
    maxRank: 1,
    grant: { kind: 'unlock_auto_relic' },
  },
  {
    id: 'unlock_sfx_pack',
    category: 'unlocks',
    name: 'SFX Pack',
    description: 'Enables retro SFX (mote pickup, combat, prestige).',
    baseCost: 5,
    maxRank: 1,
    grant: { kind: 'unlock_sfx' },
  },
  {
    id: 'unlock_dev_commands',
    category: 'unlocks',
    name: 'Tinker Mode',
    description: 'Cosmetic: shows extra debug counters in the HUD.',
    baseCost: 4,
    maxRank: 1,
    grant: { kind: 'unlock_tinker_mode' },
  },

  // ── MUTATIONS (10 nodes) ───────────────────────────────────
  {
    id: 'mutation_wardens_carry',
    category: 'mutations',
    name: 'Wardens Also Carry',
    description: 'Wardens pick up motes when no glitches are present.',
    baseCost: 20,
    maxRank: 1,
    grant: { kind: 'mutation_wardens_carry' },
  },
  {
    id: 'mutation_passive_shards',
    category: 'mutations',
    name: 'Core Whisper',
    description: 'The Core generates 1 shard per minute passively.',
    baseCost: 25,
    maxRank: 1,
    grant: { kind: 'mutation_passive_shards' },
  },
  {
    id: 'mutation_commits_are_feats',
    category: 'mutations',
    name: "Everything Is a Feature",
    description: "Every commit counts as a feat commit (summons a spirit).",
    baseCost: 30,
    maxRank: 1,
    grant: { kind: 'mutation_commits_are_feats' },
  },
  {
    id: 'mutation_double_expedition',
    category: 'mutations',
    name: 'Parallel Expeditions',
    description: 'Two expeditions can run simultaneously.',
    baseCost: 25,
    maxRank: 1,
    grant: { kind: 'mutation_double_expedition' },
  },
  {
    id: 'mutation_mote_autopickup',
    category: 'mutations',
    name: 'Magnetic Core',
    description: 'Motes auto-deliver to the Core after 10s without a Scribe.',
    baseCost: 22,
    maxRank: 1,
    grant: { kind: 'mutation_mote_autopickup' },
  },
  {
    id: 'mutation_fix_heals_glitches',
    category: 'mutations',
    name: 'Pacifist Fix',
    description: 'Fix commits make glitches flee instead of dying.',
    baseCost: 25,
    maxRank: 1,
    grant: { kind: 'mutation_fix_heals_glitches' },
  },
  {
    id: 'mutation_recursive_flow',
    category: 'mutations',
    name: 'Recursive Flow',
    description: 'Flow Cascade can trigger every 10 min instead of 20.',
    baseCost: 28,
    maxRank: 1,
    grant: { kind: 'mutation_recursive_flow' },
  },
  {
    id: 'mutation_permanent_aria',
    category: 'mutations',
    name: 'Permanent ARIA-0',
    description: 'ARIA-0 speaks in every phase, granting small passives.',
    baseCost: 35,
    maxRank: 1,
    grant: { kind: 'mutation_permanent_aria' },
  },
  {
    id: 'mutation_reverse_descent',
    category: 'mutations',
    name: 'Upward Climb',
    description: 'Prestige preserves one relic drop from the previous run.',
    baseCost: 30,
    maxRank: 1,
    grant: { kind: 'mutation_reverse_descent' },
  },
  {
    id: 'mutation_shard_bank',
    category: 'mutations',
    name: 'Shard Bank',
    description: '20% of unspent shards carry over into the next run.',
    baseCost: 30,
    maxRank: 1,
    grant: { kind: 'mutation_shard_bank' },
  },
]
