<script lang="ts">
  import { onMount } from 'svelte'
  import { bridge } from './lib/bridge/webview-bridge'
  import { initWorldStore, worldSnapshot } from './lib/stores/world-store'
  import { initCloudSyncStore } from './lib/stores/cloud-sync'
  import { initThemeStore } from './lib/theme/theme-store'
  import GameCanvas from './lib/components/GameCanvas.svelte'
  import LayerTabs from './lib/components/LayerTabs.svelte'
  import EventFeed from './lib/components/EventFeed.svelte'
  import ExpeditionPanel from './lib/components/ExpeditionPanel.svelte'
  import BuildPanel from './lib/components/BuildPanel.svelte'
  import RecruitPanel from './lib/components/RecruitPanel.svelte'
  import CommandBar from './lib/components/CommandBar.svelte'
  import PrestigeButton from './lib/components/PrestigeButton.svelte'
  import DescendButton from './lib/components/DescendButton.svelte'
  import RelicTray from './lib/components/RelicTray.svelte'
  import MetaToolbar from './lib/components/MetaToolbar.svelte'
  import TutorialOverlay from './lib/components/TutorialOverlay.svelte'

  onMount(() => {
    initThemeStore()
    bridge.init()
    initWorldStore()
    initCloudSyncStore()
  })
</script>

<main class="descent">
  {#if $worldSnapshot}
    <section class="hud">
      <span
        class="res res-tokens"
        title="Tokens — spent on Kin, buildings, and Focus abilities. Generated by Scribes carrying motes to the Core."
      >◆ {$worldSnapshot.resources.tokens}</span>
      <span
        class="res res-focus"
        title="Focus — spent on Lance/Shield/Heal commands. Gained from bug fixes and flow state."
      >✦ {$worldSnapshot.resources.focus}</span>
      <span
        class="res res-shards"
        title="Depth Shards — unlock new layers and summon bosses via DESCEND. Dropped by glitches and commits."
      >◈ {$worldSnapshot.resources.shards}</span>
      <span class="spacer"></span>
      <span
        class="phase"
        title="Drama phase — the wave rhythm. Calm → Crescendo → Climax → Dusk, on a 50-minute loop."
      >{$worldSnapshot.drama.phase}</span>
      <span
        class="run"
        title="Current run number. Prestige at MAIN to increment and spend Echoes in the Echo Tree."
      >#{$worldSnapshot.run.prestigeCount + 1}</span>
    </section>
  {:else}
    <section class="hud">
      <span class="run muted">booting…</span>
    </section>
  {/if}

  <div class="stage">
    <GameCanvas />
    <LayerTabs />
  </div>

  <div class="feed">
    <EventFeed />
  </div>

  <RecruitPanel />
  <BuildPanel />
  <ExpeditionPanel />
  <RelicTray />
  <DescendButton />
  <PrestigeButton />
  <CommandBar />
  <MetaToolbar />
  <TutorialOverlay />
</main>

<style>
  :global(:root) {
    /* Descent UI typography scale — bumped for readability */
    --desc-font-xs: 11px;
    --desc-font-sm: 12px;
    --desc-font-md: 13px;
    --desc-font-lg: 15px;
    --desc-gap-sm: 4px;
    --desc-gap-md: 8px;
    --desc-gap-lg: 12px;
  }

  :global(body) {
    margin: 0;
    padding: 0;
    background: var(--vscode-editor-background, #1e1e1e);
    color: var(--vscode-editor-foreground, #d4d4d4);
    font-family: var(--vscode-editor-font-family, 'JetBrains Mono', 'Fira Code', monospace);
    font-size: var(--desc-font-sm);
    overflow: hidden;
  }

  :global(*) { box-sizing: border-box; }

  :global(button) {
    font-family: inherit;
    font-size: var(--desc-font-sm);
  }

  .descent {
    display: flex;
    flex-direction: column;
    height: 100vh;
    background: var(--vscode-editor-background, #1e1e1e);
    color: var(--vscode-editor-foreground, #d4d4d4);
    overflow: hidden;
    min-height: 0;
  }

  .hud {
    display: flex;
    align-items: center;
    gap: var(--desc-gap-md);
    padding: 6px 10px;
    border-bottom: 1px solid var(--vscode-panel-border, #333);
    font-size: var(--desc-font-md);
    flex: 0 0 auto;
    color: var(--vscode-descriptionForeground, #888);
  }
  .hud .spacer { flex: 1 1 auto; }
  .hud .phase {
    text-transform: uppercase;
    color: var(--vscode-charts-orange, #ff8c00);
    font-size: var(--desc-font-xs);
    letter-spacing: 1px;
  }
  .hud .run { font-size: var(--desc-font-xs); }
  .muted { opacity: 0.5; }
  .res {
    display: inline-flex;
    align-items: center;
    gap: 3px;
    font-size: var(--desc-font-md);
    font-weight: 500;
  }
  .res-tokens { color: var(--vscode-charts-blue, #4daafc); }
  .res-focus  { color: var(--vscode-charts-orange, #ff8c00); }
  .res-shards { color: var(--vscode-charts-purple, #b180d7); }

  .stage {
    display: flex;
    flex: 1 1 auto;
    min-height: 0;
  }

  .feed {
    flex: 0 0 120px;
    min-height: 120px;
    max-height: 120px;
    height: 120px;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
</style>
